language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

# services:
#   - rabbitmq
#   - redis
#   - mongodb

env:
  - HELLO=World

before_install:
  - go get -v github.com/golang/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  
# script:
#   - ./scripts/pre-commit.sh
#   - go test
