language: go

go:
  - 1.11.x
  - master

# services:
#   - rabbitmq
#   - redis
#   - mongodb

env:
  - HELLO=World

before_install:
  - go get -v github.com/golang/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install: true

script:
  - dep ensure
  - ./scripts/gofmt.sh
  - go build -v ./...
  - go test -v ./...
